version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "1323:1323"
    depends_on:
      - nginx
  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
